apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: LoadBalancer
  selector:
    app: shopping-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
